#!/bin/sh

git diff --cached --diff-filter=ACM --name-only \
| grep '\.\(js\)$' \
| while read file; do
	case "$(echo "$file" | awk -F . '{print $NF}')" in
		js)
			./node_modules/.bin/jshint "$file" && \
				./node_modules/.bin/jscs "$file"
		;;
	esac

	if [ $? -ne 0 ]; then
		exit 1
	fi
done
